// Queryable field paths for the Advanced query mode — the REAL granular DB
// paths accepted by POST /api/find (derived from views.orchestrator.all_field_paths,
// offering index collapsed to ``*`` as template_of does). The Advanced path is
// the power tool: any field, any operator (is_empty / vendor_unavailable / numeric).

export const ADVANCED_FIELDS = [
  { section: "Processor", path: "cpu_offerings.*.model", label: "CPU model" },
  { section: "Processor", path: "cpu_tdp_max", label: "CPU TDP max (W)" },
  { section: "Graphics", path: "boards.*.tgp_max", label: "GPU TGP max (W)" },
  { section: "Graphics", path: "boards.*.tpp_max", label: "GPU total power max (W)" },
  { section: "Graphics", path: "boards.*.arch_marker", label: "GPU arch marker" },
  { section: "Display", path: "display_offerings.*.size_inches", label: "Display size (in)" },
  { section: "Display", path: "display_offerings.*.panel_type", label: "Panel type" },
  { section: "Display", path: "display_offerings.*.resolution_label", label: "Resolution label" },
  { section: "Display", path: "display_offerings.*.refresh_rate_hz", label: "Refresh rate (Hz)" },
  { section: "Display", path: "display_offerings.*.nits_peak", label: "Brightness (nits)" },
  { section: "Display", path: "display_offerings.*.hdr_certification", label: "HDR certification" },
  { section: "Display", path: "display_offerings.*.dci_p3_pct", label: "DCI-P3 (%)" },
  { section: "Display", path: "display_offerings.*.vrr", label: "VRR" },
  { section: "Memory", path: "memory_type", label: "Memory type" },
  { section: "Memory", path: "memory_max_gb", label: "Memory max (GB)" },
  { section: "Memory", path: "memory_speed_mts", label: "Memory speed (MT/s)" },
  { section: "Memory", path: "memory_slots", label: "Memory slots" },
  { section: "Storage", path: "storage_slots.*.gen", label: "Storage slot gen" },
  { section: "Storage", path: "storage_max_gb", label: "Storage max (GB)" },
  { section: "Camera", path: "camera_offerings.*.resolution", label: "Camera resolution" },
  { section: "Camera", path: "camera_offerings.*.ir_supported", label: "Camera IR" },
  { section: "Audio", path: "speaker_count", label: "Speaker count" },
  { section: "Audio", path: "tuning_brand", label: "Audio tuning brand" },
  { section: "Network", path: "wifi_standard", label: "Wi-Fi standard" },
  { section: "Network", path: "ethernet", label: "Ethernet" },
  { section: "Network", path: "bluetooth_version", label: "Bluetooth version" },
  { section: "I/O", path: "usbc_thunderbolt_count", label: "USB-C Thunderbolt count" },
  { section: "I/O", path: "usba_count", label: "USB-A count" },
  { section: "I/O", path: "hdmi_count", label: "HDMI count" },
  { section: "I/O", path: "hdmi_version", label: "HDMI version" },
  { section: "I/O", path: "sd_card", label: "SD card" },
  { section: "I/O", path: "audio_jack", label: "Audio jack" },
  { section: "Battery", path: "battery_offerings.*.wattage_wh", label: "Battery capacity (Wh)" },
  { section: "Battery", path: "battery_offerings.*.cell_count", label: "Battery cells" },
  { section: "Adapter", path: "adapter_offerings.*.wattage_w", label: "Adapter wattage (W)" },
  { section: "Adapter", path: "adapter_connector", label: "Adapter connector" },
  { section: "Thermals", path: "thermal_design", label: "Thermal design" },
  { section: "Thermals", path: "fan_count", label: "Fan count" },
  { section: "Dimensions", path: "width_mm", label: "Width (mm)" },
  { section: "Dimensions", path: "depth_mm", label: "Depth (mm)" },
  { section: "Dimensions", path: "height_mm_max", label: "Height max (mm)" },
  { section: "Weight", path: "weight_kg_min", label: "Weight min (kg)" },
  { section: "Weight", path: "weight_kg_max", label: "Weight max (kg)" },
  { section: "Design", path: "a_cover_material", label: "Lid material" },
  { section: "Design", path: "lighting", label: "Lighting" },
];

export const OPERATORS = [
  { op: "eq", label: "equals", needsValue: true },
  { op: "gte", label: "≥ (numeric)", needsValue: true },
  { op: "lte", label: "≤ (numeric)", needsValue: true },
  { op: "contains", label: "contains", needsValue: true },
  { op: "is_set", label: "is set", needsValue: false },
  { op: "is_empty", label: "is empty", needsValue: false },
  { op: "vendor_unavailable", label: "vendor doesn't publish", needsValue: false },
];
